/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hardwareshop;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class dtBrg extends javax.swing.JFrame {
    String sNama;
private Connection conn = new koneksi().Koneksi();
    private DefaultTableModel tabmode;
    protected void datatable(){
        Object[] Baris ={"Kode Barang","Nama Barang","Harga Barang","Jumlah Barang","Total"};
        tabmode = new DefaultTableModel(null, Baris);
        jTable1.setModel(tabmode);
        String sql= "select * from dtbarang";
    try{
        java.sql.Statement stat=conn.createStatement();
        ResultSet hasil=stat.executeQuery(sql);
        while(hasil.next()){
            String kode=hasil.getString("kode");
            String nama=hasil.getString("nmbrg");
            String hrga=hasil.getString("harga");
            String jumlh=hasil.getString("jumlh");
            String total=hasil.getString("total");
            String[] data={kode,nama,hrga,jumlh,total};
            tabmode.addRow(data);
    }
    } catch (Exception e) {
        }
    } 
    /**
     * Creates new form dtBrg
     */
    public dtBrg() {
        initComponents();
    }

    public void refreshform (){
         datatable();
        txtkode.setText("");
         txtnma.setText("");
        txthrga.setText("");
        txtjmlh.setText("");
        txttotal.setText("");
        
        txtkode.setEnabled(false);
        txtnma.setEnabled(false);
        txthrga.setEnabled(false);
        txtjmlh.setEnabled(false);
        txttotal.setEnabled(false);
        btnsimpan.setEnabled(false);
        btnedit.setEnabled(false);
        btnbatal.setEnabled(false);
        btnhapus.setEnabled(false);
        btntambah.setEnabled(true);
        btnsimpan.setText("Simpan");
       
    }
    
    private void clearform(){
        txtjmlh.setEnabled(true);
        txttotal.setEnabled(true);
        txtkode.setEnabled(false);
        txtnma.setEnabled(true);
        txthrga.setEnabled(true);
        txtjmlh.setEnabled(true);
        btnsimpan.setEnabled(true);
        btnedit.setEnabled(false);
        btnbatal.setEnabled(true);
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtnma = new javax.swing.JTextField();
        txthrga = new javax.swing.JTextField();
        btntambah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnhapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtjmlh = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Transaksi Barang");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        jLabel2.setText("Kode Barang : ");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        jLabel3.setText("Nama Barang : ");

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        jLabel4.setText("Harga Barang : ");

        txtkode.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N

        txtnma.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N

        txthrga.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N

        btntambah.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnsimpan.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnbatal.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnkeluar.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnhapus.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        jLabel5.setText("Jumlah : ");

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        jLabel6.setText("Total : ");

        txtjmlh.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        txtjmlh.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                txtjmlhMouseWheelMoved(evt);
            }
        });
        txtjmlh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtjmlhMouseClicked(evt);
            }
        });
        txtjmlh.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtjmlhInputMethodTextChanged(evt);
            }
        });
        txtjmlh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlhActionPerformed(evt);
            }
        });
        txtjmlh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtjmlhKeyPressed(evt);
            }
        });

        txttotal.setFont(new java.awt.Font("Century Schoolbook", 0, 11)); // NOI18N
        txttotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttotalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btntambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtjmlh)
                                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txthrga, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtkode)
                                    .addComponent(txtnma, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txthrga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtjmlh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnbatal))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnedit)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnkeluar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
         
        try {
            String str="SELECT * FROM dtbarang";
             PreparedStatement st = conn.prepareStatement(str);
            String sql = "SELECT * FROM dtbarang ORDER BY kode DESC";
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                String kode = rs.getString("kode").substring(2);
                String AN = "" + (Integer.parseInt(kode)+1);
                String Nol = "";

                if(AN.length()==1)
                    {Nol = "000";}
                else if(AN.length()==2)
                    {Nol = "00";}
                else if(AN.length()==3)
                    {Nol = "0";}
                else if(AN.length()==4)
                    {Nol = "";}
                txtkode.setText("CH" + Nol + AN);//sesuaikan dengan variable namenya
            } else {
                txtkode.setText("CH0001");//sesuaikan dengan variable namenya
            }
            rs.close();
          
        } catch (Exception e) {
            e.printStackTrace();//penanganan masalah
        }
        
        btntambah.setEnabled(false);
        clearform();
        
                // TODO add your handling code here:
    }//GEN-LAST:event_btntambahActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        refreshform();
        datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        double hrg = Double.parseDouble(txthrga.getText());
        int jmlh = Integer.parseInt(txtjmlh.getText());
        String kd = txtkode.getText();
        String n = txtnma.getText();
        String sql="insert into dtbarang values(?,?,?,?,?)";
        String str="SELECT * from dtbarang ";
        
        if (btnsimpan.getText().equals("Update")){
             sql="update dtbarang SET kode=?,nmbrg=?, harga=?, jumlh=?, total=? WHERE kode='"+jTable1.getValueAt(jTable1.getSelectedRow(), 0)+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, new kdbrg(kd).getkd());
                stat.setString(2, new nmbrg(n).getnm());
                stat.setString(3, txthrga.getText());
                stat.setString(4, txtjmlh.getText());
                stat.setString(5, txttotal.getText());
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Berhasil DiUpdate");
            btnsimpan.setEnabled(false);
            } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate"+e);
            }  }
        
        else {  
            sql="insert into dtbarang values(?,?,?,?,?)"; 
            
            try{
            
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, new kdbrg(kd).getkd());
            stat.setString(2, new nmbrg(n).getnm());
            stat.setString(3, txthrga.getText());
            stat.setString(4, txtjmlh.getText());
            stat.setString(5, txttotal.getText());
            stat.executeUpdate();
                        
            btnsimpan.setEnabled(false);
    } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan"+e);
        }  
        }
                   // TODO add your handling code here:
    refreshform();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        clearform();
        btnsimpan.setText("Update");
        btnedit.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        refreshform();        // TODO add your handling code here:
    }//GEN-LAST:event_btnbatalActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        txtkode.setEnabled(false);
        txtnma.setEnabled(false);
        txthrga.setEnabled(false);
        btnsimpan.setEnabled(false);
        btntambah.setEnabled(false);
        btnbatal.setEnabled(true);
        btnedit.setEnabled(true);
        btnhapus.setEnabled(true);
        
        sNama=(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1)));
        txtkode.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
        txtnma.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1))); 
        txthrga.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2)));
        txtjmlh.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 3)));
        txttotal.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 4)));
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null,"hapus","konfirmasi dialog",JOptionPane.YES_NO_OPTION);
            if (ok==0){
                String sql = "delete from dtbarang where kode = '"+ txtkode.getText()+"'";
                //mengisi nilai sql
                try{
                    PreparedStatement stat = conn.prepareStatement(sql);
                    //instance stat, mempersiapkan "sql" sebelum dieksekusi
                    stat.executeUpdate();//mengeksekusi "sql"
                    JOptionPane.showMessageDialog(null,"data berhasil dihapus");
                    refreshform(); //memanggil procedure kososng
                   }
                catch (SQLException e){
                  JOptionPane.showMessageDialog(null,"data gagal dihapus"+e);  
                }
                datatable(); //memanggil procedure datatable
            }        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void txtjmlhInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtjmlhInputMethodTextChanged
  
    // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlhInputMethodTextChanged

    private void txtjmlhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlhActionPerformed

    private void txtjmlhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjmlhKeyPressed
        
    }//GEN-LAST:event_txtjmlhKeyPressed

    private void txtjmlhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtjmlhMouseClicked
        
        
            // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlhMouseClicked

    private void txtjmlhMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_txtjmlhMouseWheelMoved
       int jmlh = Integer.parseInt(txtjmlh.getText());
        double hrg = Double.parseDouble(txthrga.getText());
        double total;
        
        total = jmlh * hrg;
        txttotal.setText(String.valueOf(total)); // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlhMouseWheelMoved

    private void txttotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttotalMouseClicked
       int jmlh = Integer.parseInt(txtjmlh.getText());
        double hrg = Double.parseDouble(txthrga.getText());
        double total;
        
        total = jmlh * hrg;
        txttotal.setText(String.valueOf(total)); // TODO add your handling code here:
    }//GEN-LAST:event_txttotalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dtBrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dtBrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dtBrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dtBrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dtBrg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txthrga;
    private javax.swing.JTextField txtjmlh;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnma;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
